// Curated chest X-rays from TBX11K (Liu et al., CVPR 2020 — CC BY 4.0).
// Images live in site/public/xray/*.webp; boxes are the ORIGINAL radiologist
// ground truth from annotations/json/TBX11K_trainval_only_tb.json, in COCO
// [x, y, w, h] form on the native 512x512 grid (NOT the VOC XML, which is at
// clinical resolution ~2840px and would produce garbage at 512 — see CLAUDE.md).
//
// GENERATED by site/scripts/build_xray_assets.py — do not hand-edit.

export type LesionClass = "Active" | "Obsolete";

export interface XrayBox {
  cls: LesionClass;
  /** COCO [x, y, w, h] on a 512x512 grid. */
  bbox: [number, number, number, number];
}

export interface Xray {
  slug: string;
  title: string;
  caption: string;
  /** Path under the Vite base, e.g. xray/tb-single.webp */
  file: string;
  /** Original path inside the TBX11K release, for provenance. */
  source: string;
  w: number;
  h: number;
  boxes: XrayBox[];
}

export const XRAYS: Xray[] = [
  {
    slug: "tb-single",
    title: "Active TB — single focal lesion",
    caption:
      "One consolidation in the patient's right upper lobe — the classic apical location for post-primary TB.",
    file: "xray/tb-single.webp",
    source: "tb/tb0285.png",
    w: 512, h: 512,
    boxes: [
      { cls: "Active", bbox: [83.4, 62.0, 164.8, 237.8] },
    ],
  },
  {
    slug: "tb-multi",
    title: "Active TB — bilateral, multifocal",
    caption:
      "Four separate active lesions across both lungs. Advanced disease: obvious once outlined, easy to under-count without.",
    file: "xray/tb-multi.webp",
    source: "tb/tb0934.png",
    w: 512, h: 512,
    boxes: [
      { cls: "Active", bbox: [93.1, 75.1, 90.5, 131.0] },
      { cls: "Active", bbox: [289.8, 91.1, 109.0, 109.4] },
      { cls: "Active", bbox: [70.9, 188.3, 117.4, 99.6] },
      { cls: "Active", bbox: [296.4, 199.7, 131.3, 92.0] },
    ],
  },
  {
    slug: "tb-obsolete",
    title: "Obsolete (inactive) TB — healed scarring",
    caption:
      "Fibrotic scarring left by a cured infection. Not contagious, needs no treatment — but at pixel level it resembles active disease. This is the hardest call in the whole task.",
    file: "xray/tb-obsolete.webp",
    source: "tb/tb0435.png",
    w: 512, h: 512,
    boxes: [
      { cls: "Obsolete", bbox: [65.0, 122.3, 162.5, 302.1] },
      { cls: "Obsolete", bbox: [289.2, 133.7, 182.6, 277.5] },
    ],
  },
  {
    slug: "healthy",
    title: "Healthy lung",
    caption:
      "No TB, no other pathology. The overwhelming majority of any screening population looks like this.",
    file: "xray/healthy.webp",
    source: "health/h0001.png",
    w: 512, h: 512,
    boxes: [],
  },
  {
    slug: "sick",
    title: "Sick, but not TB",
    caption:
      "Other pulmonary pathology. The detector fires on these 2–3x more often than on healthy lungs — the false-alarm problem that motivates a two-stage pipeline.",
    file: "xray/sick.webp",
    source: "sick/s0001.png",
    w: 512, h: 512,
    boxes: [],
  },
];

export const xray = (slug: string): Xray => {
  const x = XRAYS.find((r) => r.slug === slug);
  if (!x) throw new Error(`unknown xray: ${slug}`);
  return x;
};
