"""
build_xray_assets.py — curate the site's chest X-ray figures from TBX11K.

Reads the read-only dataset, writes two GENERATED, rebuildable things:

    site/public/xray/*.webp    the images themselves (grayscale, ~15 KB each)
    site/src/data/xrays.ts     titles, captions, provenance + ground-truth boxes

Boxes are shipped as DATA rather than burned into the pixels, so the site can
draw them as an SVG overlay and let the reader toggle them off ("can you spot
it?"). That also keeps the images small and re-annotatable.

Landmines this script respects (see CLAUDE.md):
  - data/TBX11K/ is READ-ONLY. Nothing is written back to it.
  - Boxes come from the COCO JSON (512x512 coords, matching the images), NOT
    the VOC XML, which is at original clinical resolution (~2840px) and would
    silently produce garbage boxes on a 512px image.
  - category_id 1 = ActiveTuberculosis, 2 = ObsoletePulmonaryTuberculosis.
    (3 = PulmonaryTuberculosis exists in the schema but is never used.)

Run from the repo root:

    python site/scripts/build_xray_assets.py
"""

from __future__ import annotations

import collections
import json
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parents[2]
SRC_IMGS = REPO / "data" / "TBX11K" / "imgs"
COCO = REPO / "data" / "TBX11K" / "annotations" / "json" / "TBX11K_trainval_only_tb.json"
OUT_IMGS = REPO / "site" / "public" / "xray"
OUT_TS = REPO / "site" / "src" / "data" / "xrays.ts"

CLS = {1: "Active", 2: "Obsolete", 3: "PTB"}

# The curated set. Each entry earns its place by showing the reader something the
# prose alone cannot: what the target looks like, what "cured" looks like, and
# what the two negative classes look like.
PICKS: list[tuple[str, str, str, str]] = [
    (
        "tb/tb0285.png",
        "tb-single",
        "Active TB — single focal lesion",
        "One consolidation in the patient's right upper lobe — the classic apical "
        "location for post-primary TB.",
    ),
    (
        "tb/tb0934.png",
        "tb-multi",
        "Active TB — bilateral, multifocal",
        "Four separate active lesions across both lungs. Advanced disease: obvious "
        "once outlined, easy to under-count without.",
    ),
    (
        "tb/tb0435.png",
        "tb-obsolete",
        "Obsolete (inactive) TB — healed scarring",
        "Fibrotic scarring left by a cured infection. Not contagious, needs no "
        "treatment — but at pixel level it resembles active disease. This is the "
        "hardest call in the whole task.",
    ),
    (
        "health/h0001.png",
        "healthy",
        "Healthy lung",
        "No TB, no other pathology. The overwhelming majority of any screening "
        "population looks like this.",
    ),
    (
        "sick/s0001.png",
        "sick",
        "Sick, but not TB",
        "Other pulmonary pathology. The detector fires on these 2–3x more often than "
        "on healthy lungs — the false-alarm problem that motivates a two-stage "
        "pipeline.",
    ),
]

TS_HEADER = '''// Curated chest X-rays from TBX11K (Liu et al., CVPR 2020 — CC BY 4.0).
// Images live in site/public/xray/*.webp; boxes are the ORIGINAL radiologist
// ground truth from annotations/json/TBX11K_trainval_only_tb.json, in COCO
// [x, y, w, h] form on the native 512x512 grid (NOT the VOC XML, which is at
// clinical resolution ~2840px and would produce garbage at 512 — see CLAUDE.md).
//
// GENERATED by site/scripts/build_xray_assets.py — do not hand-edit.

export type LesionClass = "Active" | "Obsolete";

export interface XrayBox {
  cls: LesionClass;
  /** COCO [x, y, w, h] on a 512x512 grid. */
  bbox: [number, number, number, number];
}

export interface Xray {
  slug: string;
  title: string;
  caption: string;
  /** Path under the Vite base, e.g. xray/tb-single.webp */
  file: string;
  /** Original path inside the TBX11K release, for provenance. */
  source: string;
  w: number;
  h: number;
  boxes: XrayBox[];
}
'''


def load_boxes() -> dict[str, list[dict]]:
    d = json.loads(COCO.read_text())

    # Re-verify the class map against the JSON rather than trusting it (the
    # convert.py step does the same and halts on mismatch).
    names = {c["id"]: c["name"] for c in d["categories"]}
    if names.get(1) != "ActiveTuberculosis" or names.get(2) != "ObsoletePulmonaryTuberculosis":
        raise SystemExit(f"category map changed under us: {names}")

    imgs = {i["id"]: i for i in d["images"]}
    by = collections.defaultdict(list)
    for a in d["annotations"]:
        by[a["image_id"]].append(a)

    out: dict[str, list[dict]] = {}
    for iid, anns in by.items():
        out[imgs[iid]["file_name"]] = [
            {"cls": CLS[a["category_id"]], "bbox": [round(v, 1) for v in a["bbox"]]}
            for a in anns
        ]
    return out


def main() -> None:
    boxes_for = load_boxes()
    OUT_IMGS.mkdir(parents=True, exist_ok=True)

    records = []
    for rel, slug, title, caption in PICKS:
        src = SRC_IMGS / rel
        if not src.exists():
            raise SystemExit(f"missing source image: {src}")
        im = Image.open(src).convert("L")
        dst = OUT_IMGS / f"{slug}.webp"
        im.save(dst, "WEBP", quality=82, method=6)
        records.append(
            {
                "slug": slug,
                "title": title,
                "caption": caption,
                "file": f"xray/{slug}.webp",
                "source": rel,
                "w": im.size[0],
                "h": im.size[1],
                "boxes": boxes_for.get(rel, []),
            }
        )
        kb = dst.stat().st_size / 1024
        print(f"  {slug:12s} {im.size[0]}x{im.size[1]}  {kb:5.1f} KB  boxes={len(records[-1]['boxes'])}")

    lines = [TS_HEADER, "export const XRAYS: Xray[] = ["]
    for r in records:
        lines.append("  {")
        lines.append(f'    slug: "{r["slug"]}",')
        lines.append(f'    title: "{r["title"]}",')
        lines.append(f'    caption:\n      "{r["caption"]}",')
        lines.append(f'    file: "{r["file"]}",')
        lines.append(f'    source: "{r["source"]}",')
        lines.append(f'    w: {r["w"]}, h: {r["h"]},')
        if not r["boxes"]:
            lines.append("    boxes: [],")
        else:
            lines.append("    boxes: [")
            for b in r["boxes"]:
                bb = ", ".join(str(v) for v in b["bbox"])
                lines.append(f'      {{ cls: "{b["cls"]}", bbox: [{bb}] }},')
            lines.append("    ],")
        lines.append("  },")
    lines.append("];")
    lines.append("")
    lines.append("export const xray = (slug: string): Xray => {")
    lines.append("  const x = XRAYS.find((r) => r.slug === slug);")
    lines.append("  if (!x) throw new Error(`unknown xray: ${slug}`);")
    lines.append("  return x;")
    lines.append("};")
    lines.append("")

    OUT_TS.write_text("\n".join(lines))
    total = sum(f.stat().st_size for f in OUT_IMGS.glob("*.webp")) / 1024
    print(f"\n→ {OUT_TS.relative_to(REPO)}")
    print(f"→ {OUT_IMGS.relative_to(REPO)}/  ({total:.1f} KB total)")


if __name__ == "__main__":
    main()
